# Generated by Django 5.0.3 on 2024-05-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disc', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_on',
            new_name='booked_on',
        ),
    ]
